Update travis code: remove multiline.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,19 +6,10 @@ dist: trusty
 language: c
 
 script:
-  - |
-    # Execute the script with the defaults (which is, download the terraform
-    # binary for Linux)
-    bash -x download_terraform_binaries.sh
-
-  - |
-    # Check if there's a file in the expected location, fail otherwise
-    if [ ! -f ./bins/linux/terraform ]; then
-      echo -e "Failed! File \"terraform\" not found."
-      exit 1
+  - bash -x download_terraform_binaries.sh
+  - if [ ! -f ./bins/linux/terraform ]; then
+      echo -e "Failed! File \"terraform\" not found.";
+      exit 1;
     fi
-
-  - |
-    # As an extra sanity check, check if we can get the terraform version
-    ./bins/linux/terraform -v
+  - ./bins/linux/terraform -v
 
